Start Transaction;
insert into driver_has_type (User_id, Type_id) values(7,1);
insert into driver_has_type (User_id, Type_id) values(8,3);
insert into driver_has_type (User_id, Type_id) values(9,2);
insert into driver_has_type (User_id, Type_id) values(10,2);
insert into driver_has_type (User_id, Type_id) values(11,1);
commit;
Start Transaction;
insert into driver_has_type (User_id, Type_id) values(7,3);
insert into driver_has_type (User_id, Type_id) values(8,4);
insert into driver_has_type (User_id, Type_id) values(9,4);
insert into driver_has_type (User_id, Type_id) values(10,2);
insert into driver_has_type (User_id, Type_id) values(11,4);
commit;
Start Transaction;
insert into driver_has_type (User_id, Type_id) values(7,1);
insert into driver_has_type (User_id, Type_id) values(8,4);
insert into driver_has_type (User_id, Type_id) values(9,5);
insert into driver_has_type (User_id, Type_id) values(10,2);
insert into driver_has_type (User_id, Type_id) values(11,4);
commit;
Start Transaction;
insert into driver_has_type (User_id, Type_id) values(7,2);
insert into driver_has_type (User_id, Type_id) values(8,4);
insert into driver_has_type (User_id, Type_id) values(9,1);
insert into driver_has_type (User_id, Type_id) values(10,4);
insert into driver_has_type (User_id, Type_id) values(11,3);
commit;
