start transaction;
insert into transport (Model_id, regPlate) values (1, "000");
insert into transport (Model_id, regPlate) values (2, "001");
insert into transport (Model_id, regPlate) values (3, "002");
insert into transport (Model_id, regPlate) values (4, "003");
insert into transport (Model_id, regPlate) values (5, "004");
insert into transport (Model_id, regPlate) values (1, "005");
insert into transport (Model_id, regPlate) values (2, "006");
insert into transport (Model_id, regPlate) values (3, "007");
insert into transport (Model_id, regPlate) values (4, "008");
commit;