start transaction;
insert into user (fullName, birthday, position, contractId, login, password) VALUES("admin", "1970-01-01","admin",0,"admin","admin");
insert into user (fullName, birthday, position, contractId, login, password) VALUES("testUser2","1970-01-01","Conductor",3,"testUser2","testUser2");
insert into user (fullName, birthday, position, contractId, login, password) VALUES("testUser3","1970-01-01","Conductor",4,"testUser3","testUser3");
insert into user (fullName, birthday, position, contractId, login, password) VALUES("testUser4","1970-01-01","Conductor",5,"testUser4","testUser4");
insert into user (fullName, birthday, position, contractId, login, password) VALUES("testUser5","1970-01-01","Conductor",6,"testUser5","testUser5");
insert into user (fullName, birthday, position, contractId, login, password) VALUES("testUser6","1970-01-01","Conductor",7,"testUser6","testUser6");
insert into user (fullName, birthday, position, contractId, login, password) VALUES("testUser7","1970-01-01","Driver",8,"testUser7","testUser7");
insert into user (fullName, birthday, position, contractId, login, password) VALUES("testUser8","1970-01-01","Driver",9,"testUser8","testUser8");
insert into user (fullName, birthday, position, contractId, login, password) VALUES("testUser9","1970-01-01","Driver",10,"testUser9","testUser9");
insert into user (fullName, birthday, position, contractId, login, password) VALUES("testUser10","1970-01-01","Driver",11,"testUser10","testUser10");
insert into user (fullName, birthday, position, contractId, login, password) VALUES("testUser11","1970-01-01","Driver",12,"testUser11","testUser11");
commit;
